project:
  type: website

website:
  page-navigation: true
  title: "Analysis of Compound Extreme Events"
  twitter-card: true
  repo-url: https://github.com/javedali99/website-nas-project
  repo-actions: [edit, issue]
  page-footer: 
    center: "&copy; Copyright 2022, Javed Ali. All rights reserved" 
    right: 
      - icon: github
        href: https://github.com/javedali99/
      - icon: twitter 
        href: https://twitter.com/javedali99/ 
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        file: index.qmd
      - text: "Data Collection & Processing"
        file: data-processing.qmd
      - text: "Analysis"
        file: tutorials.qmd
      - text: "About"
        file: about.qmd
      # - text: "References"
      #   file: reference.qmd

    right:
      - icon: twitter
        href: https://twitter.com/javedali99
        aria-label: Twitter
      - icon: github
        href: https://github.com/javedali99
        aria-label: GitHub

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      contents:
        - tutorials.qmd
        - tutorial-1.qmd
        - tutorial-2.qmd

    - title: "Data Processing"
      contents:
        - data-processing.qmd
        # navigation items

    - title: "Fundamentals"
      contents:
        - fundamentals.qmd
        # navigation items

    - title: "Reference"
      contents:
        - reference.qmd
        # navigation items
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



     
    