project:
  type: website

website:
  site-url: "https://compound-extremes-analysis.netlify.app/"
  # google-analytics: "UA-XXXXXXXX"
  page-navigation: true
  title: "Analysis of Compound Extreme Events"
  opengraph: true
  twitter-card:
    image: "/images/henkdeboer_nl.png"
  repo-url: https://github.com/javedali99/NAS-project-website
  repo-actions: [edit, issue]
  page-footer: 
    center: "&copy; Copyright 2022, Javed Ali. All rights reserved" 
    right: 
      - icon: github
        href: https://github.com/javedali99/
      - icon: twitter 
        href: https://twitter.com/javedali99/ 
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data Processing"
        href: docs/data/index.qmd
      - text: "Analysis"
        href: docs/analysis/index.qmd
      - text: "Results"
        href: docs/results/index.qmd
      - text: "About"
        href: about.qmd
      # - text: "References"
      #   file: reference.qmd

    right:
      - icon: twitter
        href: https://twitter.com/javedali99
        aria-label: Twitter
      - icon: github
        href: https://github.com/javedali99
        aria-label: GitHub

  sidebar:
    - id: analysis
      title: "Analysis"
      style: "floating"
      collapse-level: 3
      align: left
      # background: light
      contents:
        - docs/analysis/index.qmd
        - text: "Dates of Events"
          href: docs/analysis/sheldus-events-dates.qmd
        - text: "Individual Time Series"
          href: docs/analysis/raw-ts-creation.qmd
        - text: "Percentile Calculation"
          href: docs/analysis/percentiles.qmd
        - text: "Percentiles with SHELDUS Dates"
          href: docs/analysis/sheldus-percentiles.qmd


    - id: data
      title: "Data Processing"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - docs/data/index.qmd
        - text: "Data collection"
          href: docs/data/download-data.qmd
        - text: "Data processing"
          href: docs/data/processing-data.qmd
        # navigation items

    - id: data-viz
      title: "Results"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - docs/results/index.qmd
        - text: "Heatmaps"
          href: docs/results/heatmaps.qmd
        - text: "Mapping"
          href: docs/results/mapping.qmd
        # navigation items

    - title: "Reference"
      contents:
        - reference.qmd
        # navigation items
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



     
    